version: "3"
services:
  infotrygd-joark-mottak:
      build: .
      image: navikt/journalfoering-mottak:latest
      environment:
        PROFILE: local
      env_file:
        - secrets.properties
      ports:
        - "8086:8080"
